name: promptweaver build and publish

on:
  push:
    paths:
      - 'promptweaver/**'
  workflow_dispatch:

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pdm install

      - name: Publish package distributions to PyPI
        run: pdm publish --repository https://test.pypi.org/legacy/