name: promptweaver build and publish

on:
  push:
    tags:
      - 'python/*'
  workflow_dispatch:

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: ./promptweaver
        run: pdm install

      - name: Publish package distributions to PyPI
        working-directory: ./promptweaver
        run: pdm publish